version: 2

jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/giveaway-misc
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: build wheel
          command: |
            set -euxo

            python3.8 -m pip install wheel
            python3.8 setup.py bdist_wheel

      - add_ssh_keys:
          fingerprints:
            - "42:3d:45:0f:a1:bd:1e:82:a7:fd:a1:45:4b:38:c8:1b"

      - run:
          name: deploy to ed5rpzdi.lax.bluespan.gg
          command: |
            set -euxo

            cat << EOF >> ~/.ssh/known_hosts
            ed5rpzdi.lax.bluespan.gg,2001:19f0:6001:509f:5400:2ff:fe6b:19ff,45.77.68.171 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPTWYlTdGuLMakaC14VBZ6dYAVB/iGT6VPt8qvGrQGuLWIvAZyQO+nRBlkslmHQiAZFr7/V9P/q2C+0pKdYtHMs=
            EOF

            wheel="$(echo dist/*.whl)"

            scp "$wheel" deploy@ed5rpzdi.lax.bluespan.gg:/home/deploy/wheels/
            ssh deploy@ed5rpzdi.lax.bluespan.gg python3.8 -m pip install --user --upgrade "/home/deploy/wheels/$(basename $wheel)"
